databases:
  - name: expensetracker_db
    databaseName: expensetracker_db
    user: expensetracker

services:
  - type: web
    name: expense-tracker-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expensetracker_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        